# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 230bfcb6b61f8cb2c37443156c9a66a525f3d52a729f2d915dc5dee10ef6d134c1bf674425f4e56c0cffc1b44c515b577167fbb37463e545ffdbd0fd67916962

test:
  secret_key_base: 22c890bacf38a57e0d200037e8825f09237e04aef8ab762d4064b4def49bea6b74e69fd1721efbeca2c7364d79bfaf1a61570fa9ff40440f74889a0da72f05e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
